name: Coveralls

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.9.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.9.0
      - name: yarn, compile, hint, coverage
        run: |
          yarn
          yarn compile
          yarn hint
          yarn coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
